### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by 3rd-Eden** [Swaagie/npm-probe#2]
```
Error: Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
    at bailout (/root/browsenpm/plugins/npm-probe.js:252:9)
    at prepped (/root/browsenpm/plugins/npm-probe.js:42:23)
    at database (/root/browsenpm/plugins/npm-probe.js:191:23)
    at /root/browsenpm/node_modules/cradle/lib/cradle/database/index.js:21:13
    at Request._onResponse [as _callback] (/root/browsenpm/node_modules/cradle/lib/cradle.js:214:20)
    at self.callback (/root/browsenpm/node_modules/request/request.js:121:22)
    at Request.EventEmitter.emit (events.js:95:17)
    at ClientRequest.self.clientErrorHandler (/root/browsenpm/node_modules/request/request.js:230:10)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
error: Forever detected script exited with code: 8
error: Script restart attempt #40
```

Could be intentional and exepcted to crash here. But browsenpm crashed looped on this about 900+ times on the 27th of May. Most likely due to an unreachable database. We could implement some sort of temporary local storage of the stats or only serving the cached metics in some way.

For example we could store a JSON snapshot of this data in the package that npm-probe publishes so if couchdb is failing we can fallback to this static data..

(Just throwing thoughts around here)

**Comment by indexzero** [comment]
It is a slow crash loop that causes everything to be down.

```
Error: Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketOnEnd [as onend] (http.js:1568:23)
    at Socket.g (events.js:180:16)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)
    at bailout (/root/browsenpm/plugins/npm-probe.js:252:9)
    at fetched (/root/browsenpm/plugins/npm-probe.js:50:25)
    at /root/browsenpm/node_modules/async/lib/async.js:592:17
    at done (/root/browsenpm/node_modules/async/lib/async.js:129:15)
    at /root/browsenpm/node_modules/async/lib/async.js:32:16
    at /root/browsenpm/node_modules/async/lib/async.js:589:21
    at final (/root/browsenpm/plugins/npm-probe.js:238:23)
    at done (/root/browsenpm/node_modules/async/lib/async.js:129:15)
    at /root/browsenpm/node_modules/async/lib/async.js:32:16
    at store (/root/browsenpm/plugins/npm-probe.js:225:25)
error: Forever detected script exited with code: 8
error: Script restart attempt #1

Error: Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
    at bailout (/root/browsenpm/plugins/npm-probe.js:252:9)
    at fetched (/root/browsenpm/plugins/npm-probe.js:50:25)
    at /root/browsenpm/node_modules/async/lib/async.js:592:17
    at done (/root/browsenpm/node_modules/async/lib/async.js:129:15)
    at /root/browsenpm/node_modules/async/lib/async.js:32:16
    at /root/browsenpm/node_modules/async/lib/async.js:589:21
    at final (/root/browsenpm/plugins/npm-probe.js:238:23)
    at done (/root/browsenpm/node_modules/async/lib/async.js:129:15)
    at /root/browsenpm/node_modules/async/lib/async.js:32:16
    at store (/root/browsenpm/plugins/npm-probe.js:225:25)
error: Forever detected script exited with code: 8
error: Script restart attempt #2
```
